version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_visualizer
    ports:
    - "5001:5000"
    volumes: 
    - .:/project
    environment:
      FLASK_ENV: development
